import os
import re
import sys
import glob
import asyncio
from typing import List, Dict, Set
from datetime import datetime

# Import KBJ2 Core
from company import GLMAgentEngine, ProjectManager, AutonomousCompany, ProjectType
from personas import ORGANIZATION

# Paths
SDMS_ROOT = r"F:\genmini\sdms\src"
ROUTES_FILE = os.path.join(SDMS_ROOT, "config", "routes.ts")
REPORT_PATH = r"F:\genmini\sdms\MAP_CONNECTIVITY_REPORT.md"

class ConnectivityAuditor:
    """
    Frontend Connectivity Auditor
    - Parses routes.ts to find 'Active Pages'
    - Scans filesystem to find 'Physical Pages'
    - Identifies Orphans and Broken Links
    """
    
    def __init__(self):
        self.active_routes: Dict[str, str] = {} # path -> component_name
        self.imports: Dict[str, str] = {}       # component_name -> file_path
        self.physical_pages: Set[str] = set()
        self.orphans: List[str] = []
        
    def scan_routes(self):
        """Parse routes.ts to find defined routes and imports"""
        print(f"🔍 [Auditor] Scanning Routes: {ROUTES_FILE}")
        
        with open(ROUTES_FILE, "r", encoding="utf-8") as f:
            content = f.read()
            
        # 1. Parse Lazy Imports
        # const BomLayout = lazy(() => import('@/components/bom/BomLayout'));
        import_pattern = re.compile(r"const\s+(\w+)\s*=\s*lazy\(\(\)\s*=>\s*import\(['\"]@/([^'\"]+)['\"]\)")
        for match in import_pattern.finditer(content):
            comp_name, path = match.groups()
            self.imports[comp_name] = path.replace("/", "\\")
            
        # 2. Parse Route Definitions
        # { path: '/bom', component: BomLayout },
        route_pattern = re.compile(r"path:\s*['\"]([^'\"]+)['\"],\s*component:\s*(\w+)")
        for match in route_pattern.finditer(content):
            path, comp_name = match.groups()
            self.active_routes[path] = comp_name
            
        print(f"   - Found {len(self.active_routes)} active routes")
        print(f"   - Found {len(self.imports)} component imports")

    def scan_filesystem(self):
        """Scan physical directory for likely pages"""
        print(f"🔍 [Auditor] Scanning Filesystem: {SDMS_ROOT}")
        
        # Look for typical page indicators
        patterns = [
            "**/*Page.tsx", 
            "**/*Layout.tsx", 
            "**/*Dashboard.tsx", 
            "**/*Manager.tsx",
            "**/*App.tsx"
        ]
        
        for pattern in patterns:
            # Recursive glob
            files = glob.glob(os.path.join(SDMS_ROOT, pattern), recursive=True)
            for f in files:
                rel_path = os.path.relpath(f, SDMS_ROOT).replace(".tsx", "")
                self.physical_pages.add(rel_path)
                
        print(f"   - Found {len(self.physical_pages)} physical page candidates")

    def analyze(self):
        """Compare Routes vs Files"""
        print("📊 [Auditor] Interpreting Connectivity...")
        
        connected_files = set()
        
        # Check if imported files actually exist
        for comp, import_path in self.imports.items():
            # Handle potential .then() wrappers or sub-paths
            clean_path = import_path
            
            # Marking as connected
            # We need to match loose paths because import might be 'components/bom/BomLayout' 
            # while file is 'components/bom/BomLayout.tsx'
            for p in self.physical_pages:
                if clean_path in p or p in clean_path:
                    connected_files.add(p)
        
        # Find Orphans
        for p in self.physical_pages:
            if p not in connected_files:
                self.orphans.append(p)
                
        print(f"   - Verified Connected: {len(connected_files)}")
        print(f"   - Potential Orphans: {len(self.orphans)}")

    def generate_report(self):
        """Generate Markdown Report"""
        
        report = f"""# 🔗 SDMS Frontend Connectivity Report
**Generated By:** KBJ2 Corp (ConnectivityAuditor)
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Target:** `F:\\genmini\\sdms`

## 1. Active Route Topology
Detected {len(self.active_routes)} active routes in `src/config/routes.ts`.

| Route Path | Component | Status |
|---|---|---|
"""
        for path, comp in self.active_routes.items():
            status = "✅ Linked" if comp in self.imports else "❌ Missing Import"
            report += f"| `{path}` | **{comp}** | {status} |\n"
            
        report += f"""
## 2. Orphan Analysis
Files detected as Page/Dashboard/Layout but **NOT** linked in `routes.ts`.
(These might be used as sub-components or strictly internal tools)

"""
        if self.orphans:
            for orphan in self.orphans:
                report += f"- ⚠️ `{orphan}.tsx`\n"
        else:
            report += "- ✅ No orphans detected. Clean architecture.\n"
            
        report += "\n## 3. Commander's Verdict\n"
        if len(self.orphans) > 5:
            report += "**⚠️ Architecture Warning**: Many unreferenced 'Page-like' components found. Check if they are legacy or sub-views."
        else:
            report += "**✅ System Healthy**: Most components are correctly wired."

        with open(REPORT_PATH, "w", encoding="utf-8") as f:
            f.write(report)
            
        return REPORT_PATH

async def run_kbj2_audit():
    print("🏢 [KBJ2 Corp] Starting Frontend Audit Mission...")
    
    # Init Core Logic
    auditor = ConnectivityAuditor()
    
    # 1. Execute Logic
    auditor.scan_routes()
    auditor.scan_filesystem()
    auditor.analyze()
    report_file = auditor.generate_report()
    
    # 2. Simulate KBJ2 Agent Review (Just for flavor/logic verification)
    # In a real scenario, we would feed 'report_file' content to GLM-4
    print(f"\n📢 [QA Team] Audit Complete.")
    print(f"📄 Report generated at: {report_file}")
    
    # 3. Update MAP.MD if needed (Simple append)
    with open(r"F:\genmini\sdms\MAP.MD", "a", encoding="utf-8") as f:
        f.write("\n\n---\n## 🔍 5. Connectivity Audit (Latest)\n")
        f.write(f"See detailed report: [MAP_CONNECTIVITY_REPORT](file://{report_file})\n")
        f.write(f"- Active Routes: {len(auditor.active_routes)}\n")
        f.write(f"- Potential Orphans: {len(auditor.orphans)}\n")

if __name__ == "__main__":
    asyncio.run(run_kbj2_audit())
